#!/bin/bash

REPORT_DIR="$(dirname "$0")/../reports"
TXT_REPORT="$REPORT_DIR/security-report.txt"
HTML_REPORT="$REPORT_DIR/security-report.html"

PASS=$(grep "^PASS :" "$TXT_REPORT" | awk '{print $3}')
FAIL=$(grep "^FAIL :" "$TXT_REPORT" | awk '{print $3}')
TOTAL=$((PASS + FAIL))

if [ "$TOTAL" -gt 0 ]; then
    COMPLIANCE=$((PASS * 100 / TOTAL))
else
    COMPLIANCE=0
fi

cat > "$HTML_REPORT" <<EOF
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>Linux Security Compliance Report</title>
<style>
body {
    font-family: Arial, sans-serif;
    margin: 40px;
    background: #f5f5f5;
}

.container {
    max-width: 1000px;
    margin: auto;
    background: white;
    padding: 30px;
    border-radius: 8px;
}

h1 {
    margin-bottom: 10px;
}

.summary {
    display: flex;
    gap: 20px;
    margin: 20px 0;
}

.card {
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 6px;
    min-width: 150px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 30px;
}

th, td {
    border: 1px solid #ddd;
    padding: 10px;
    text-align: left;
}

th {
    background: #eee;
}

.pass {
    font-weight: bold;
}

.fail {
    font-weight: bold;
}
</style>
</head>

<body>

<div class="container">

<h1>Linux Security Compliance Report</h1>

<p>Generated by Linux Security Compliance Automation</p>

<div class="summary">

<div class="card">
<strong>Total Checks</strong>
<h2>$TOTAL</h2>
</div>

<div class="card">
<strong>PASS</strong>
<h2>$PASS</h2>
</div>

<div class="card">
<strong>FAIL</strong>
<h2>$FAIL</h2>
</div>

<div class="card">
<strong>Compliance</strong>
<h2>$COMPLIANCE%</h2>
</div>

</div>

<table>

<tr>
<th>ID</th>
<th>Check</th>
<th>Result</th>
</tr>

EOF

grep -E '^\[(PASS|FAIL)\]' "$TXT_REPORT" | while read -r line
do
    RESULT=$(echo "$line" | awk '{print $1}' | tr -d '[]')
    ID=$(echo "$line" | awk '{print $2}')
    NAME=$(echo "$line" | cut -d' ' -f4-)

    if [ "$RESULT" = "PASS" ]; then
        CLASS="pass"
    else
        CLASS="fail"
    fi

    cat >> "$HTML_REPORT" <<EOF
<tr>
<td>$ID</td>
<td>$NAME</td>
<td class="$CLASS">$RESULT</td>
</tr>
EOF

done

cat >> "$HTML_REPORT" <<EOF

</table>

</div>

</body>
</html>
EOF

echo "HTML report generated:"
echo "$HTML_REPORT"
